---
name: Check Collection

on:
  schedule:
    - cron: '0 22 * * *'

  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash

jobs:

  build:
    name: Run installation script
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install --yes gcc make chezscheme libgmp3-dev nodejs
      - name: Checkout pack
        uses: actions/checkout@v3
        with:
          repository: stefan-hoeck/idris2-pack
      - name: Run MicroPack
        run: |
          make micropack SCHEME="chezscheme"
          echo "$HOME/.pack/bin" >> "$GITHUB_PATH"
      - name: Build pack-admin
        run: $HOME/.pack/bin/pack --no-prompt build pack-admin.ipkg
      - name: Extract Collection from HEAD
        run: build/exec/pack-admin --no-prompt extract-from-head "$HOME/.pack/db/testdb.toml"
      - name: Check Collection
        run: |
          mkdir -p docs
          mkdir "$HOME/output"
          build/exec/pack-admin --no-prompt check-collection testdb "$HOME/output/STATUS.md"
      - name: Checkout pack-docs
        uses: actions/checkout@v3
        if: always()
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Copy collection
        if: always()
        run: cp -ua "$HOME/output/docs/*" "docs/"
      - name: Commit files
        if: always()
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "*.css" "*.html"
          git commit -m "[ docs ] API docs update" -m "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
